/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersRouteRouteImport } from './routes/users/route'
import { Route as LoginRouteRouteImport } from './routes/login/route'
import { Route as InitializeRouteRouteImport } from './routes/initialize/route'
import { Route as ConfigurationRouteRouteImport } from './routes/configuration/route'
import { Route as Certificate_requestsRouteRouteImport } from './routes/certificate_requests/route'
import { Route as Certificate_authoritiesRouteRouteImport } from './routes/certificate_authorities/route'
import { Route as IndexRouteImport } from './routes/index'

const UsersRouteRoute = UsersRouteRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRouteRoute = LoginRouteRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InitializeRouteRoute = InitializeRouteRouteImport.update({
  id: '/initialize',
  path: '/initialize',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigurationRouteRoute = ConfigurationRouteRouteImport.update({
  id: '/configuration',
  path: '/configuration',
  getParentRoute: () => rootRouteImport,
} as any)
const Certificate_requestsRouteRoute =
  Certificate_requestsRouteRouteImport.update({
    id: '/certificate_requests',
    path: '/certificate_requests',
    getParentRoute: () => rootRouteImport,
  } as any)
const Certificate_authoritiesRouteRoute =
  Certificate_authoritiesRouteRouteImport.update({
    id: '/certificate_authorities',
    path: '/certificate_authorities',
    getParentRoute: () => rootRouteImport,
  } as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/certificate_authorities': typeof Certificate_authoritiesRouteRoute
  '/certificate_requests': typeof Certificate_requestsRouteRoute
  '/configuration': typeof ConfigurationRouteRoute
  '/initialize': typeof InitializeRouteRoute
  '/login': typeof LoginRouteRoute
  '/users': typeof UsersRouteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/certificate_authorities': typeof Certificate_authoritiesRouteRoute
  '/certificate_requests': typeof Certificate_requestsRouteRoute
  '/configuration': typeof ConfigurationRouteRoute
  '/initialize': typeof InitializeRouteRoute
  '/login': typeof LoginRouteRoute
  '/users': typeof UsersRouteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/certificate_authorities': typeof Certificate_authoritiesRouteRoute
  '/certificate_requests': typeof Certificate_requestsRouteRoute
  '/configuration': typeof ConfigurationRouteRoute
  '/initialize': typeof InitializeRouteRoute
  '/login': typeof LoginRouteRoute
  '/users': typeof UsersRouteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/certificate_authorities'
    | '/certificate_requests'
    | '/configuration'
    | '/initialize'
    | '/login'
    | '/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/certificate_authorities'
    | '/certificate_requests'
    | '/configuration'
    | '/initialize'
    | '/login'
    | '/users'
  id:
    | '__root__'
    | '/'
    | '/certificate_authorities'
    | '/certificate_requests'
    | '/configuration'
    | '/initialize'
    | '/login'
    | '/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  Certificate_authoritiesRouteRoute: typeof Certificate_authoritiesRouteRoute
  Certificate_requestsRouteRoute: typeof Certificate_requestsRouteRoute
  ConfigurationRouteRoute: typeof ConfigurationRouteRoute
  InitializeRouteRoute: typeof InitializeRouteRoute
  LoginRouteRoute: typeof LoginRouteRoute
  UsersRouteRoute: typeof UsersRouteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/initialize': {
      id: '/initialize'
      path: '/initialize'
      fullPath: '/initialize'
      preLoaderRoute: typeof InitializeRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuration': {
      id: '/configuration'
      path: '/configuration'
      fullPath: '/configuration'
      preLoaderRoute: typeof ConfigurationRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certificate_requests': {
      id: '/certificate_requests'
      path: '/certificate_requests'
      fullPath: '/certificate_requests'
      preLoaderRoute: typeof Certificate_requestsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certificate_authorities': {
      id: '/certificate_authorities'
      path: '/certificate_authorities'
      fullPath: '/certificate_authorities'
      preLoaderRoute: typeof Certificate_authoritiesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  Certificate_authoritiesRouteRoute: Certificate_authoritiesRouteRoute,
  Certificate_requestsRouteRoute: Certificate_requestsRouteRoute,
  ConfigurationRouteRoute: ConfigurationRouteRoute,
  InitializeRouteRoute: InitializeRouteRoute,
  LoginRouteRoute: LoginRouteRoute,
  UsersRouteRoute: UsersRouteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
