package server

import (
	"encoding/json"
	"errors"
	"io"
	"net/http"
	"strconv"
	"time"

	"github.com/canonical/notary/internal/cluster"
	"github.com/canonical/notary/internal/db"
	"go.uber.org/zap"
)

// defaultJoinTokenTTL is how long a join token stays valid when the caller does
// not say. Join tokens are transferred out of band, so the window is kept short:
// long enough for an operator to paste it into a provisioning step, not long
// enough to sit forgotten in a shell history.
const defaultJoinTokenTTL = time.Hour

// maxJoinTokenTTL bounds what an operator may ask for. A join token is on its
// own sufficient to obtain a cluster certificate, so it must never be a
// long-lived credential (spec §1.2).
const maxJoinTokenTTL = 24 * time.Hour

type ClusterMemberResponse struct {
	// ID is the dqlite node ID as a decimal string; it does not fit an int64.
	ID      string `json:"id"`
	Name    string `json:"name"`
	Address string `json:"address"`
	Role    string `json:"role"`
	Leader  bool   `json:"leader"`
}

type ClusterStatusResponse struct {
	Enabled bool   `json:"enabled"`
	NodeID  string `json:"node_id"`
	Address string `json:"address"`
	// LeaderID is empty while the cluster has no leader, which is what a client
	// sees during an election or a quorum loss.
	LeaderID string                  `json:"leader_id"`
	Voters   int                     `json:"voters"`
	Members  []ClusterMemberResponse `json:"members"`
}

type CreateJoinTokenParams struct {
	// Role is the role the new member should end up holding: "voter" or
	// "standby". Empty means standby.
	Role string `json:"role"`
	// TTLSeconds bounds the token's lifetime. Empty means defaultJoinTokenTTL.
	TTLSeconds int64 `json:"ttl_seconds"`
}

type CreateJoinTokenResponse struct {
	// Token is returned exactly once, here. Only its hash is stored.
	Token     string `json:"token"`
	Role      string `json:"role"`
	ExpiresAt int64  `json:"expires_at"`
}

type JoinClusterParams struct {
	Token string `json:"token"`
	// Address is the address the joining node will advertise to its peers. The
	// signed certificate is bound to it.
	Address string `json:"address"`
	// CSR is the PEM encoded certificate signing request generated by the
	// joining node. Only its public key is used.
	CSR string `json:"csr"`
}

type JoinClusterResponse struct {
	Certificate   string   `json:"certificate"`
	CACertificate string   `json:"ca_certificate"`
	Role          string   `json:"role"`
	MemberAddress []string `json:"member_addresses"`
}

// clusterEnabled reports whether the cluster API can serve this request, writing
// the error response itself when it cannot.
func clusterEnabled(w http.ResponseWriter, env *HandlerDependencies) bool {
	if env.ClusterNode == nil {
		writeResponse(w, http.StatusNotFound, "clustering is not enabled", nil, env.SystemLogger)
		return false
	}
	return true
}

// ListClusterMembers reports every dqlite member, joined with the
// operator-assigned names Notary stores for them.
func ListClusterMembers(env *HandlerDependencies) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		if !clusterEnabled(w, env) {
			return
		}

		members, err := collectClusterMembers(r, env)
		if err != nil {
			env.SystemLogger.Error("failed to list cluster members", zap.Error(err))
			writeResponse(w, http.StatusInternalServerError, "failed to list cluster members", nil, env.SystemLogger)
			return
		}

		writeResponse(w, http.StatusOK, "", members, env.SystemLogger)
	}
}

// GetClusterStatus reports the cluster's aggregate health from this node's point
// of view.
func GetClusterStatus(env *HandlerDependencies) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		if !clusterEnabled(w, env) {
			return
		}

		members, err := collectClusterMembers(r, env)
		if err != nil {
			env.SystemLogger.Error("failed to read cluster status", zap.Error(err))
			writeResponse(w, http.StatusInternalServerError, "failed to read cluster status", nil, env.SystemLogger)
			return
		}

		status := ClusterStatusResponse{
			Enabled: true,
			NodeID:  strconv.FormatUint(env.ClusterNode.ID(), 10),
			Address: env.ClusterNode.Address(),
			Members: members,
		}
		for _, member := range members {
			if member.Role == string(cluster.RoleVoter) {
				status.Voters++
			}
			if member.Leader {
				status.LeaderID = member.ID
			}
		}

		writeResponse(w, http.StatusOK, "", status, env.SystemLogger)
	}
}

// CreateClusterJoinToken issues a single-use join token. The token is returned
// once and never again: only its hash is stored.
func CreateClusterJoinToken(env *HandlerDependencies) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		if !clusterEnabled(w, env) {
			return
		}

		var params CreateJoinTokenParams
		// An empty body is valid: it asks for a standby token with the default TTL.
		if err := json.NewDecoder(r.Body).Decode(&params); err != nil && !errors.Is(err, io.EOF) {
			writeResponse(w, http.StatusBadRequest, "invalid request body", nil, env.SystemLogger)
			return
		}

		role, err := parseClusterRole(params.Role)
		if err != nil {
			writeResponse(w, http.StatusBadRequest, err.Error(), nil, env.SystemLogger)
			return
		}

		ttl := defaultJoinTokenTTL
		if params.TTLSeconds != 0 {
			ttl = time.Duration(params.TTLSeconds) * time.Second
		}
		if ttl <= 0 || ttl > maxJoinTokenTTL {
			writeResponse(w, http.StatusBadRequest, "ttl_seconds must be between 1 second and 24 hours", nil, env.SystemLogger)
			return
		}

		token, hash, err := cluster.GenerateJoinToken()
		if err != nil {
			env.SystemLogger.Error("failed to generate cluster join token", zap.Error(err))
			writeResponse(w, http.StatusInternalServerError, "failed to create join token", nil, env.SystemLogger)
			return
		}

		now := time.Now().UTC()
		expiresAt := now.Add(ttl)
		if _, err := env.Database.CreateClusterJoinToken(hash, role, now, expiresAt); err != nil {
			env.SystemLogger.Error("failed to store cluster join token", zap.Error(err))
			writeResponse(w, http.StatusInternalServerError, "failed to create join token", nil, env.SystemLogger)
			return
		}

		writeResponse(w, http.StatusCreated, "", CreateJoinTokenResponse{
			Token:     token,
			Role:      string(role),
			ExpiresAt: expiresAt.Unix(),
		}, env.SystemLogger)
	}
}

// JoinCluster signs a joining node's certificate signing request in exchange for
// a valid join token, and hands back the peer list it needs to reach the
// cluster.
//
// This endpoint is deliberately not behind session authentication: a node that
// has not joined yet has no account and no cluster certificate. The join token
// is the credential, which is why it is single-use and short-lived.
func JoinCluster(env *HandlerDependencies) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		if !clusterEnabled(w, env) {
			return
		}

		var params JoinClusterParams
		if err := json.NewDecoder(r.Body).Decode(&params); err != nil {
			writeResponse(w, http.StatusBadRequest, "invalid request body", nil, env.SystemLogger)
			return
		}
		if params.Token == "" || params.Address == "" || params.CSR == "" {
			writeResponse(w, http.StatusBadRequest, "token, address and csr are required", nil, env.SystemLogger)
			return
		}

		role, err := env.Database.RedeemClusterJoinToken(cluster.HashJoinToken(params.Token), time.Now().UTC())
		if err != nil {
			if errors.Is(err, db.ErrNotFound) {
				// Unknown, expired and already-used tokens are all reported the
				// same way so a caller learns nothing about which tokens exist.
				env.SystemLogger.Warn("rejected cluster join with an invalid token", zap.String("address", params.Address))
				writeResponse(w, http.StatusUnauthorized, "invalid or expired join token", nil, env.SystemLogger)
				return
			}
			env.SystemLogger.Error("failed to redeem cluster join token", zap.Error(err))
			writeResponse(w, http.StatusInternalServerError, "failed to process join request", nil, env.SystemLogger)
			return
		}

		certPEM, caCertPEM, err := cluster.SignJoinRequest(env.ClusterConfig.StateDir, []byte(params.CSR), params.Address)
		if err != nil {
			env.SystemLogger.Error("failed to sign cluster join request", zap.Error(err))
			writeResponse(w, http.StatusBadRequest, "failed to sign the certificate request", nil, env.SystemLogger)
			return
		}

		members, err := env.ClusterNode.Members(r.Context())
		if err != nil {
			env.SystemLogger.Error("failed to list cluster members", zap.Error(err))
			writeResponse(w, http.StatusInternalServerError, "failed to process join request", nil, env.SystemLogger)
			return
		}
		addresses := make([]string, 0, len(members))
		for _, member := range members {
			addresses = append(addresses, member.Address)
		}

		env.SystemLogger.Info("signed a cluster join request",
			zap.String("address", params.Address), zap.String("role", string(role)))

		writeResponse(w, http.StatusOK, "", JoinClusterResponse{
			Certificate:   string(certPEM),
			CACertificate: string(caCertPEM),
			Role:          string(role),
			MemberAddress: addresses,
		}, env.SystemLogger)
	}
}

// PromoteClusterMember forces a member to voter ahead of dqlite's own role
// convergence.
func PromoteClusterMember(env *HandlerDependencies) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		if !clusterEnabled(w, env) {
			return
		}

		id, ok := clusterMemberID(w, r, env)
		if !ok {
			return
		}

		if err := env.ClusterNode.Promote(r.Context(), id); err != nil {
			env.SystemLogger.Error("failed to promote cluster member", zap.Error(err), zap.Uint64("node_id", id))
			writeResponse(w, http.StatusInternalServerError, "failed to promote cluster member", nil, env.SystemLogger)
			return
		}

		writeResponse(w, http.StatusOK, "cluster member promoted", nil, env.SystemLogger)
	}
}

// DeleteClusterMember removes a member from the cluster and drops its name
// record. Beyond the graceful handover below it is a passthrough to dqlite's own
// Remove: Notary adds no quorum projection or safety checks of its own
// (spec §1.5).
//
// Without ?force=true the member's Raft responsibilities are handed over first,
// which is what makes decommissioning a live member cheap. force exists for the
// case the handover cannot work: a member that is already gone.
func DeleteClusterMember(env *HandlerDependencies) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		if !clusterEnabled(w, env) {
			return
		}

		id, ok := clusterMemberID(w, r, env)
		if !ok {
			return
		}

		force := r.URL.Query().Get("force") == "true"
		if !force {
			if err := env.ClusterNode.Handover(r.Context(), id); err != nil {
				env.SystemLogger.Error("failed to hand over cluster member responsibilities",
					zap.Error(err), zap.Uint64("node_id", id))
				writeResponse(w, http.StatusInternalServerError,
					"failed to hand over the cluster member's responsibilities, retry with force to remove it anyway",
					nil, env.SystemLogger)
				return
			}
		}

		if err := env.ClusterNode.Remove(r.Context(), id); err != nil {
			env.SystemLogger.Error("failed to remove cluster member", zap.Error(err), zap.Uint64("node_id", id))
			writeResponse(w, http.StatusInternalServerError, "failed to remove cluster member", nil, env.SystemLogger)
			return
		}

		// The member is already out of the cluster at this point; a stale name
		// record is cosmetic, so it must not turn a successful removal into a
		// failed request.
		if err := env.Database.DeleteClusterMember(strconv.FormatUint(id, 10)); err != nil && !errors.Is(err, db.ErrNotFound) {
			env.SystemLogger.Error("removed cluster member but failed to delete its name record",
				zap.Error(err), zap.Uint64("node_id", id))
		}

		writeResponse(w, http.StatusOK, "cluster member removed", nil, env.SystemLogger)
	}
}

// collectClusterMembers merges dqlite's view of the cluster with the names
// Notary recorded, and marks the current leader.
func collectClusterMembers(r *http.Request, env *HandlerDependencies) ([]ClusterMemberResponse, error) {
	members, err := env.ClusterNode.Members(r.Context())
	if err != nil {
		return nil, err
	}

	// A missing name record is not an error: the member is in the cluster
	// either way, and reporting it namelessly is more useful than failing.
	names := map[string]string{}
	if records, err := env.Database.ListClusterMembers(); err != nil {
		env.SystemLogger.Warn("failed to read cluster member names", zap.Error(err))
	} else {
		for _, record := range records {
			names[record.NodeID] = record.Name
		}
	}

	var leaderID uint64
	if leader, err := env.ClusterNode.Leader(r.Context()); err != nil {
		env.SystemLogger.Warn("failed to identify the cluster leader", zap.Error(err))
	} else if leader != nil {
		leaderID = leader.ID
	}

	response := make([]ClusterMemberResponse, 0, len(members))
	for _, member := range members {
		id := strconv.FormatUint(member.ID, 10)
		response = append(response, ClusterMemberResponse{
			ID:      id,
			Name:    names[id],
			Address: member.Address,
			Role:    string(member.Role),
			Leader:  leaderID != 0 && member.ID == leaderID,
		})
	}

	return response, nil
}

// clusterMemberID reads the dqlite node ID out of the request path, writing the
// error response itself when it is unusable.
func clusterMemberID(w http.ResponseWriter, r *http.Request, env *HandlerDependencies) (uint64, bool) {
	id, err := strconv.ParseUint(r.PathValue("id"), 10, 64)
	if err != nil {
		writeResponse(w, http.StatusBadRequest, "invalid cluster member id", nil, env.SystemLogger)
		return 0, false
	}
	return id, true
}

// parseClusterRole validates the role requested for a join token. An empty role
// means standby, which is the role every member joins with (spec §1.3).
func parseClusterRole(role string) (db.ClusterRole, error) {
	switch db.ClusterRole(role) {
	case "", db.ClusterRoleStandBy:
		return db.ClusterRoleStandBy, nil
	case db.ClusterRoleVoter:
		return db.ClusterRoleVoter, nil
	default:
		return "", errors.New(`role must be "voter" or "standby"`)
	}
}
