name: notary
base: core24
adopt-info: notary-release-data
summary: Notary is a certificate management tool.
license: Apache-2.0
description: |
  Notary is a simple, reliable, and secure certificate management tool.

  Use it to request, approve, and manage certificate requests for your services. 

grade: stable
confinement: strict

issues: https://github.com/canonical/notary/issues
source-code: https://github.com/canonical/notary

apps:
  notary:
    command: bin/notary
    plugs:
      - network
      - network-bind
      - home
  notaryd:
    daemon: simple
    install-mode: disable
    command: bin/notaryd-start
    refresh-mode: endure
    plugs:
      - network
      - network-bind

parts:
  dqlite:
    source: https://github.com/canonical/dqlite
    source-type: git
    source-depth: 1
    source-tag: v1.17.0
    plugin: autotools
    autotools-configure-parameters:
      - --prefix=
      - --enable-build-raft
    stage-packages:
      - libuv1
      - libsqlite3-0
      - liblz4-1
    build-packages:
      - make
      - libuv1-dev
      - liblz4-dev
      - libsqlite3-dev
      - pkg-config
    organize:
      usr/lib/: lib/
    prime:
      - lib/libdqlite*so*
      - lib/libraft*so*
      - lib/*/libuv*so*

  notary:
    after: [dqlite]
    plugin: go
    source: .
    source-type: local
    build-snaps:
      - go/1.26/stable
      - node/20/stable
    build-environment:
      - GOTOOLCHAIN: local
      - CGO_CFLAGS: -I${CRAFT_STAGE}/include/ -I${CRAFT_STAGE}/usr/local/include/
      - CGO_LDFLAGS: -L${CRAFT_STAGE}/lib/ -L${CRAFT_STAGE}/usr/local/lib/
    override-build: |
      npm install --prefix ui
      npm run build --prefix ui
      craftctl default

  notary-release-data:
    plugin: nil
    source: .
    override-build: |
      version="$(cat version/VERSION)"
      craftctl set version="$version"

  service-files:
    plugin: dump
    source: service
