name: Frontend Build

on:
  workflow_call:

jobs:
  vite-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ui
    steps:
      - uses: actions/checkout@v6
      - name: use bun
        uses: oven-sh/setup-bun@v2

      - name: install dependencies
        run: |
          bun install
      - name: format and lint
        run: |
          bun run ci
      - name: build
        run: |
          bun run build
      - name: Upload frontend files
        uses: actions/upload-artifact@v7
        with:
          name: frontend-static-files
          path: ui/dist
