name: Go Lint

on:
  workflow_call:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-go@v6
        with:
          go-version-file: "go.mod"

      - uses: ./.github/actions/install-dqlite

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v9.3.0
        with:
          version: v2.12.2
