name: Run Gosec

permissions:
  contents: read

on:
    workflow_call:

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
      - uses: actions/checkout@v6

      - name: Run Gosec Security Scanner
        uses: securego/gosec@4a3bd8af174872c778439083ded7adbf3747e770 # v2.26.1
