name: Run Gosec

permissions:
  contents: read

on:
    workflow_call:

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
      - uses: actions/checkout@v4

      - name: Run Gosec Security Scanner
        uses: securego/gosec@223e19b8856e00f02cc67804499a83f77e208f3c # v2.25.0
