name: Go Vet

on:
  workflow_call:

jobs:
  go-vet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-go@v6
        with:
          go-version-file: "go.mod"
      - uses: ./.github/actions/setup-dqlite

      - name: Go vet
        run: go vet ./...