name: Rock Build

on:
  workflow_call:

jobs:
  build-rock:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - uses: canonical/craft-actions/rockcraft-pack@main
        id: rockcraft
        with:
          rockcraft-channel: edge
      - name: Install pre-requisites
        run: |
          sudo apt-get update
          sudo apt-get install -y openssl jq
      - name: Import the image to Docker registry
        run: |
          sudo rockcraft.skopeo --insecure-policy copy oci-archive:${{ steps.rockcraft.outputs.rock }} docker-daemon:notary:latest
      - uses: actions/upload-artifact@v4
        if: steps.test_notify.outcome == 'success'
        with:
          name: rock
          path: ${{ steps.rockcraft.outputs.rock }}
