name: Rock Build

on:
  workflow_call:

jobs:
  build-rock:
    strategy:
      matrix:
        arch:
          - arch: amd64
            runner: ubuntu-22.04
          - arch: arm64
            runner: [self-hosted, linux, ARM64, medium, jammy]
    runs-on: ${{ matrix.arch.runner }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - uses: canonical/craft-actions/rockcraft-pack@main
        id: rockcraft
        with:
          rockcraft-channel: edge
      - uses: actions/upload-artifact@v4
        with:
          name: rock-${{ matrix.arch.arch }}
          path: ${{ steps.rockcraft.outputs.rock }}
